[versions]
kotlin = "2.1.20"
#https://github.com/google/ksp/releases
ksp = "2.1.20-2.0.1"
gmazzoBuildconfig = "3.0.3"
#https://github.com/JetBrains/compose-multiplatform/releases
compose = "1.8.0"
#https://developer.android.google.cn/develop/ui/compose/bom/bom-mapping?hl=el
composeBom = "2025.04.01"
#https://klibs.io/project/Kotlin/kotlinx.coroutines
kotlinx-coroutines = "1.10.2"
apache-sshd = "2.15.0"
lifecycle = "2.8.4"
hilt = "2.51.1"
slf4j = "2.0.17"
logback = "1.5.18"
#https://repo1.maven.org/maven2/io/github/oshai/
kotlin-logging = "7.0.7"
kodein = "7.26.0"
koin-bom = "4.1.0-Beta8"
#https://klibs.io/project/Kotlin/kotlinx.serialization
kotlin-serializable = "1.8.1"
datastore = "1.1.5"
junit = "5.9.2"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

apache-sshd-mina = { module = "org.apache.sshd:sshd-mina", version.ref = "apache-sshd" }
apache-sshd-core = { module = "org.apache.sshd:sshd-core", version.ref = "apache-sshd" }
apache-sshd-common = { module = "org.apache.sshd:sshd-common", version.ref = "apache-sshd" }
apache-sshd-putty = { module = "org.apache.sshd:sshd-putty", version.ref = "apache-sshd" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
kodein-di-jvm = { module = "org.kodein.di:kodein-di-jvm", version.ref = "kodein" }
kodein-di-conf-jvm = { module = "org.kodein.di:kodein-di-conf-jvm", version.ref = "kodein" }
kodein-di-framework-android-x = { module = "org.kodein.di:kodein-di-framework-android-x", version.ref = "kodein" }
kodein-di-framework-compose = { module = "org.kodein.di:kodein-di-framework-compose", version.ref = "kodein" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serializable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serializable" }
datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

gmazzo-buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gmazzoBuildconfig" }
